/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.suanimsatici;

import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKayit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnArti = new javax.swing.JButton();
        btnEksi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnMiktarGoster = new javax.swing.JButton();
        cmbAmount = new javax.swing.JComboBox<>();
        lblIcilenMiktar = new javax.swing.JLabel();
        lblKalanMiktar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblHedef = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        btnKayit.setBackground(new java.awt.Color(153, 204, 255));
        btnKayit.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        btnKayit.setText("Kayıtlar");
        btnKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Hoşgeldiniz!");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\icons8-drinking-48.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Vücudumuzun neredeyse dörtte üçünü oluşturan");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("su, insan sağlığının devamı için oldukça faydalı.");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Günlük alınması gereken miktarın altında su tüketildiği ");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("zaman,bazı sağlık sorunlarına davetiye çıkabilir. ");

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Günde 1,5-3 litre arası su tüketmelisiniz.");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\icons8-curved-arrow-16.png")); // NOI18N

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 3, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Kayıtlarınıza buradan ulaşabilirsiniz");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKayit)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKayit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        btnArti.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\icons8-plus-math-16.png")); // NOI18N
        btnArti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtiActionPerformed(evt);
            }
        });

        btnEksi.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\eksi.png")); // NOI18N
        btnEksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksiActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\icons8-soda-water-64 (1).png")); // NOI18N

        btnMiktarGoster.setBackground(new java.awt.Color(204, 204, 204));
        btnMiktarGoster.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        btnMiktarGoster.setText("Seç");
        btnMiktarGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiktarGosterActionPerformed(evt);
            }
        });

        cmbAmount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miktarı Seçin", "1500", "2400", "3000" }));
        cmbAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAmountActionPerformed(evt);
            }
        });

        lblIcilenMiktar.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        lblIcilenMiktar.setText("0");

        lblKalanMiktar.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        lblKalanMiktar.setText("0");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        jLabel12.setText("Kalan Miktar:");

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        jLabel13.setText("İçilen Miktar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEksi)
                                    .addComponent(jLabel12))
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnArti)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIcilenMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblKalanMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnMiktarGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHedef, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHedef)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMiktarGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnArti)
                    .addComponent(btnEksi))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblIcilenMiktar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblKalanMiktar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    SqlClass sql=new SqlClass();
    private void miktarArttırma(){
            if(Hedef!=icilenMiktar){
                    if(icilenMiktar==0){                   
                    icilenMiktar+=150; 
                    lblIcilenMiktar.setText(String.valueOf(icilenMiktar));
                    KalanMiktar=Hedef-icilenMiktar;
                    lblKalanMiktar.setText(String.valueOf(KalanMiktar));
                    sql.Ekle();
                    }
                    else if(icilenMiktar>0){                
                     icilenMiktar+=150; 
                     lblIcilenMiktar.setText(String.valueOf(icilenMiktar));
                     KalanMiktar=Hedef-icilenMiktar;
                     lblKalanMiktar.setText(String.valueOf(KalanMiktar));
                    sql.Guncelle(); 
                    }
                }
    }
    private void miktarAzaltma(){
        if(icilenMiktar==150){
             icilenMiktar-=150;
             sql.Sil();
             lblIcilenMiktar.setText(String.valueOf(icilenMiktar));                        
             KalanMiktar+=150;
             lblKalanMiktar.setText(String.valueOf(KalanMiktar));
        }
        else{
             icilenMiktar-=150;
             lblIcilenMiktar.setText(String.valueOf(icilenMiktar));                        
             KalanMiktar+=150;
             lblKalanMiktar.setText(String.valueOf(KalanMiktar));
             sql.Guncelle();
        }
    }
int Hedef=0;
int KalanMiktar=0;
int icilenMiktar=0;
    private void btnArtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtiActionPerformed
       int amount=cmbAmount.getSelectedIndex();
        switch (amount) {
            case 1:
                Hedef=1500;
              miktarArttırma();             
                break;
            case 2:
                Hedef=2400;
               miktarArttırma();
                break;
            case 3:
                Hedef=3000;
                miktarArttırma();
                break;
            default: 
                 JOptionPane.showMessageDialog(null,"Miktar giriniz!");
                break;
        }
     
        
 
    }//GEN-LAST:event_btnArtiActionPerformed

    private void btnEksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksiActionPerformed
        // TODO add your handling code here:
        int amount=cmbAmount.getSelectedIndex();
        if(icilenMiktar>0){
            switch (amount) {
                case 1:
                    Hedef=1500;
                   miktarAzaltma();
                    break;
                case 2:
                    Hedef=2400;
                     miktarAzaltma();
                    break;
                case 3:
                    Hedef=3000;
                       miktarAzaltma();
                    break;
                default:
                    JOptionPane.showMessageDialog(null,"Miktar giriniz!");
                    break;
            }
        }
    }//GEN-LAST:event_btnEksiActionPerformed

    private void btnMiktarGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiktarGosterActionPerformed
        // TODO add your handling code here:
        lblHedef.setVisible(false);
        int amount=cmbAmount.getSelectedIndex();
        switch (amount) {
            case 1: 
              lblHedef.setText(String.valueOf(1500));            
                break;
            case 2:
                lblHedef.setText(String.valueOf(2400));
                break;
            case 3:
                lblHedef.setText(String.valueOf(3000));
                break;
            default:
            JOptionPane.showMessageDialog(null,"Miktar giriniz!");
                break;
                
        } 
    }//GEN-LAST:event_btnMiktarGosterActionPerformed

    private void btnKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitActionPerformed
        // TODO add your handling code here:;
         this.setVisible(false);
         Kayitlar k=new Kayitlar();
         Kayitlar.cmbIkiMiktar.setSelectedIndex(cmbAmount.getSelectedIndex());
         Kayitlar.lblIkiHedef.setText(lblHedef.getText());
         Kayitlar.lblIkiIcilen.setText(lblIcilenMiktar.getText());
         Kayitlar.lblIkiKalan.setText(lblKalanMiktar.getText());
         Kayitlar.lblIkiHedef.setVisible(false);
         Kayitlar.lblIkiIcilen.setVisible(false);
         Kayitlar.lblIkiKalan.setVisible(false);
         Kayitlar.cmbIkiMiktar.setVisible(false);
         k.setVisible(true);
    }//GEN-LAST:event_btnKayitActionPerformed

    private void cmbAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });     
        
        
          for(int i=1;i<3;i++){
           Thread.sleep(3000*10);
           JOptionPane.showMessageDialog(null, "Su içmeyi unutmayınız!");
          }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArti;
    private javax.swing.JButton btnEksi;
    private javax.swing.JButton btnKayit;
    private javax.swing.JButton btnMiktarGoster;
    public static javax.swing.JComboBox<String> cmbAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblHedef;
    public static javax.swing.JLabel lblIcilenMiktar;
    public static javax.swing.JLabel lblKalanMiktar;
    // End of variables declaration//GEN-END:variables
}
